
spring:
  application:
    name: member-service

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
logging:
  level:
    ROOT: INFO
    com.springcloud.memberserviceopenfeign.client.*: debug
feign:
  okhttp:
    enabled: false
  httpclient:
    enabled: true
  client:
    config:
      default:
        loggerLevel: HEADERS
        connectTimeout: 15000 #\u5BA2\u6237\u7AEF\u5411\u5FAE\u670D\u52A1\u53D1\u8D77\u94FE\u63A5\u7684\u6700\u957F\u7B49\u5F85\u65F6\u95F4
        readTimeout: 15000 #\u8FDE\u63A5\u540E\uFF0C\u7B49\u5F85\u54CD\u5E94\u8FD4\u56DE\u7684\u6700\u957F\u65F6\u95F4
      book-service:
        loggerLebel: HEADERS
        connectTimeout: 5000 #\u5BA2\u6237\u7AEF\u5411\u5FAE\u670D\u52A1\u53D1\u8D77\u94FE\u63A5\u7684\u6700\u957F\u7B49\u5F85\u65F6\u95F4
        readTimeout: 5000 #\u8FDE\u63A5\u540E\uFF0C\u7B49\u5F85\u54CD\u5E94\u8FD4\u56DE\u7684\u6700\u957F\u65F6\u95F4
debug: true