spring:
  application:
    name: member-service
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
book-service: #\u6CE8\u518Cid
  ribbon: #\u9488\u5BF9\u4E8E\u67D0\u4E2A\u5FAE\u670D\u52A1\u8FDB\u884C\u8BBE\u7F6E
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule